version: '3.4'

services:
  ci-build:
    image: microsoft/aspnetcore:2.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./Microservice.sln && dotnet publish ./Microservice.sln -c Release -o ./obj/Docker/publish"
