version: '3.4'

networks:
  microservice-bridge-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.0.0/16
    
services:
  identity-db:
    image: mysql:5.7
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_PASSWORD=12345678
      - MYSQL_USER=IdentityServer
      - MYSQL_DATABASE=IdentityServer
    networks:
      microservice-bridge-network:
        ipv4_address: 192.168.0.103
    container_name: microservice.identity.db

  services-queue:
    build:
      context: .
      dockerfile: Dockerfile-RabbitMQ
    ports:
      - 15672:15672
    networks:
      microservice-bridge-network:
        ipv4_address: 192.168.0.101
    container_name: microservice.services.queue

  services-db:
    image: mongo:4.1.1
    ports:
      - 27017:27017
    networks:
      microservice-bridge-network:
        ipv4_address: 192.168.0.100
    container_name: microservice.services.db

  services-redis:
    image: redis:4.0.11
    ports:
      - 6379:6379
    networks:
      microservice-bridge-network:
        ipv4_address: 192.168.0.102
    container_name: microservice.services.redis