version: '3.5'

networks:
  microservice-network:
    name: microservice-network
    driver: bridge

services:
  microservice.identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    ports:
      - 5001:80
    networks:
      - microservice-network

  microservice.logging.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    ports:
      - 5002:80
    networks:
      - microservice-network

  microservice.logging.backgroundprocess:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    networks:
      - microservice-network

  microservice.notification.backgroundprocess:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    dns:
      - 8.8.8.8
    networks:
      - microservice-network

  ezstore.microservice.product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    networks:
      - microservice-network