version: '3.4'

services:
  microservice.identityserver:
    image: microservice.identityserver
    container_name: microservice-identityserver
    build:
      target: deploy
      context: 02.CoreServices/Member/Microservice.IdentityServer
      dockerfile: Dockerfile.deploy

  microservice.logging.api:
    image: microservice.logging.api
    container_name: microservice-logging-api
    build:
      target: deploy
      context: 02.CoreServices/Logging/Microservice.Logging.API
      dockerfile: Dockerfile.deploy

  microservice.setting.api:
    image: microservice.setting.api
    container_name: microservice-setting-api
    build:
      target: deploy
      context: 02.CoreServices/Setting/Microservice.Setting.API
      dockerfile: Dockerfile.deploy

  microservice.logging.backgroundprocess:
    image: microservice.logging.background
    container_name: microservice-logging-background
    build:
      target: deploy
      context: 02.CoreServices/Logging/Microservice.Logging.BackgroundProcess
      dockerfile: Dockerfile.deploy

  microservice.notification.backgroundprocess:
    image: microservice.notification.background
    container_name: microservice-notification-background
    build:
      target: deploy
      context: 02.CoreServices/Notification/Microservice.Notification.BackgroundProcess
      dockerfile: Dockerfile.deploy
    dns:
      - 8.8.8.8

  ezstore.order.api:
    image: ezstore.order.api
    container_name: ezstore-order-api
    build:
      target: deploy
      context: 03.ezStore/Order/ezStore.Order.API
      dockerfile: Dockerfile.deploy

  ezstore.payment.api:
    image: ezstore.payment.api
    container_name: ezstore-payment-api
    build:
      target: deploy
      context: 03.ezStore/Payment/ezStore.Payment.API
      dockerfile: Dockerfile.deploy

  ezstore.product.api:
    image: ezstore.product.api
    container_name: ezstore-product-api
    build:
      target: deploy
      context: 03.ezStore/Product/ezStore.Product.API
      dockerfile: Dockerfile.deploy

  ezstore.warehouse.api:
    image: ezstore.warehouse.api
    container_name: ezstore-warehouse-api
    build:
      target: deploy
      context: 03.ezStore/WareHouse/ezStore.WareHouse.API
      dockerfile: Dockerfile.deploy
