version: '3.5'

networks:
  microservice-network:
    name: microservice-network
    driver: bridge

services:
  ezStore.webui:
    image: ezstore.webui
    container_name: ezstore-webui
    build:
      context: 03.ezStore\WebUI
      dockerfile: dockerfile
    ports:
      - 8001:80
    networks:
      - microservice-network