version: '3.4'

networks:
  microservice-bridge-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.0.0/16
    
services:
  identity-db:
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    build:
      context: .
      dockerfile: Dockerfile-MySql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_PASSWORD=12345678
      - MYSQL_USER=IdentityServer
      - MYSQL_DATABASE=IdentityServer
    networks:
      microservice-bridge-network:
        ipv4_address: 192.168.0.103

  services-queue:
    build:
      context: .
      dockerfile: Dockerfile-RabbitMQ
    ports:
      - 15673:15672
      - 5673:5672
    networks:
      microservice-bridge-network:
        ipv4_address: 192.168.0.101

  services-db:
    build:
      context: .
      dockerfile: Dockerfile-MongoDB
    ports:
      - 27017:27017
    networks:
      microservice-bridge-network:
        ipv4_address: 192.168.0.100

  services-redis:
    build:
      context: .
      dockerfile: Dockerfile-Redis
    ports:
      - 6379:6379
    networks:
      microservice-bridge-network:
        ipv4_address: 192.168.0.102