version: '3.4'

services:
  ezstore.microservice.product.api:
    image: ezstore.product.api
    container_name: ezstore-product-api
    build:
      target: deploy
      context: 03.ezStore/Product/ezStore.Microservice.Product.API
      dockerfile: Dockerfile.deploy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 26005:80
    command: /bin/bash -c "dotnet ezStore.Microservice.Product.API.dll"

  microservice.identityserver:
    image: microservice.identity.server
    container_name: microservice-identity-server
    build:
      target: deploy
      context: 02.CoreServices/Member/Microservice.IdentityServer
      dockerfile: Dockerfile.deploy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 25001:80
    command: /bin/bash -c "dotnet Microservice.IdentityServer.dll"

  microservice.logging.api:
    image: microservice.logging.api
    container_name: microservice-logging-api
    build:
      target: deploy
      context: 02.CoreServices/Logging/Microservice.Logging.API
      dockerfile: Dockerfile.deploy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 25002:80
    command: /bin/bash -c "dotnet Microservice.Logging.API.dll"

  microservice.logging.backgroundprocess:
    image: microservice.logging.background
    container_name: microservice-logging-background
    build:
      target: deploy
      context: 02.CoreServices/Logging/Microservice.Logging.BackgroundProcess
      dockerfile: Dockerfile.deploy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command: /bin/bash -c "dotnet Microservice.Logging.BackgroundProcess.dll"

  microservice.notification.backgroundprocess:
    image: microservice.notification.background
    container_name: microservice-notification-background
    build:
      target: deploy
      context: 02.CoreServices/Notification/Microservice.Notification.BackgroundProcess
      dockerfile: Dockerfile.deploy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    dns:
      - 8.8.8.8
    command: /bin/bash -c "dotnet Microservice.Notification.BackgroundProcess.dll"
