apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: microservices-identityserver-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 30001
      name: http
      protocol: HTTP
    hosts:
    - "microservices.identityserver"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: microservices-identityserver
spec:
  hosts:
  - "microservices.identityserver"
  gateways:
  - microservices-identityserver-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: microservices-identityserver
        port:
          number: 80
---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ezstore-product-api-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 30002
      name: http
      protocol: HTTP
    hosts:
    - "ezstore.productapi"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ezstore-product-api
spec:
  hosts:
  - "ezstore.productapi"
  gateways:
  - ezstore-product-api-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: ezstore-product-api
        port:
          number: 80
---